//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java.metamodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.massfords.humantask.Named;
import com.massfords.humantask.Visitable;
import com.massfords.humantask.Visitor;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Cache complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cache"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="level" type="{f4g/schemas/java/MetaModel}CacheLevel"/&gt;
 *         &lt;element name="size" type="{f4g/schemas/java/MetaModel}RAMSize"/&gt;
 *         &lt;element name="computedPower" type="{f4g/schemas/java/MetaModel}Power" minOccurs="0"/&gt;
 *         &lt;element name="hitRatio" type="{f4g/schemas/java/MetaModel}HitRatio" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cache", propOrder = {
    "level",
    "size",
    "computedPower",
    "hitRatio"
})
public class Cache implements Cloneable, Named, Visitable, CopyTo
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "int")
    protected CacheLevel level;
    @XmlElement(required = true)
    @XmlSchemaType(name = "double")
    protected RAMSize size;
    @XmlSchemaType(name = "double")
    protected Power computedPower;
    @XmlSchemaType(name = "double")
    protected HitRatio hitRatio;
    @XmlTransient
    private QName jaxbElementName;

    /**
     * Default no-arg constructor
     * 
     */
    public Cache() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Cache(final CacheLevel level, final RAMSize size, final Power computedPower, final HitRatio hitRatio, final QName jaxbElementName) {
        this.level = level;
        this.size = size;
        this.computedPower = computedPower;
        this.hitRatio = hitRatio;
        this.jaxbElementName = jaxbElementName;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link CacheLevel }
     *     
     */
    public CacheLevel getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheLevel }
     *     
     */
    public void setLevel(CacheLevel value) {
        this.level = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link RAMSize }
     *     
     */
    public RAMSize getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link RAMSize }
     *     
     */
    public void setSize(RAMSize value) {
        this.size = value;
    }

    /**
     * Gets the value of the computedPower property.
     * 
     * @return
     *     possible object is
     *     {@link Power }
     *     
     */
    public Power getComputedPower() {
        return computedPower;
    }

    /**
     * Sets the value of the computedPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Power }
     *     
     */
    public void setComputedPower(Power value) {
        this.computedPower = value;
    }

    /**
     * Gets the value of the hitRatio property.
     * 
     * @return
     *     possible object is
     *     {@link HitRatio }
     *     
     */
    public HitRatio getHitRatio() {
        return hitRatio;
    }

    /**
     * Sets the value of the hitRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitRatio }
     *     
     */
    public void setHitRatio(HitRatio value) {
        this.hitRatio = value;
    }

    public void setJAXBElementName(QName name) {
        this.jaxbElementName = name;
    }

    public QName getJAXBElementName() {
        return this.jaxbElementName;
    }

    public void afterUnmarshal(Unmarshaller u, Object parent) {
        if (parent instanceof JAXBElement) {
            this.jaxbElementName = ((JAXBElement) parent).getName();
        }
    }

    public void accept(Visitor aVisitor) {
        aVisitor.visit(this);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof Cache) {
            final Cache copy = ((Cache) draftCopy);
            if (this.level!= null) {
                CacheLevel sourceLevel;
                sourceLevel = this.getLevel();
                CacheLevel copyLevel = ((CacheLevel) strategy.copy(LocatorUtils.property(locator, "level", sourceLevel), sourceLevel));
                copy.setLevel(copyLevel);
            } else {
                copy.level = null;
            }
            if (this.size!= null) {
                RAMSize sourceSize;
                sourceSize = this.getSize();
                RAMSize copySize = ((RAMSize) strategy.copy(LocatorUtils.property(locator, "size", sourceSize), sourceSize));
                copy.setSize(copySize);
            } else {
                copy.size = null;
            }
            if (this.computedPower!= null) {
                Power sourceComputedPower;
                sourceComputedPower = this.getComputedPower();
                Power copyComputedPower = ((Power) strategy.copy(LocatorUtils.property(locator, "computedPower", sourceComputedPower), sourceComputedPower));
                copy.setComputedPower(copyComputedPower);
            } else {
                copy.computedPower = null;
            }
            if (this.hitRatio!= null) {
                HitRatio sourceHitRatio;
                sourceHitRatio = this.getHitRatio();
                HitRatio copyHitRatio = ((HitRatio) strategy.copy(LocatorUtils.property(locator, "hitRatio", sourceHitRatio), sourceHitRatio));
                copy.setHitRatio(copyHitRatio);
            } else {
                copy.hitRatio = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new Cache();
    }

}
