//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java.metamodel;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.massfords.humantask.Visitable;
import com.massfords.humantask.Visitor;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for HardDisk complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HardDisk"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{f4g/schemas/java/MetaModel}StorageUnit"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rpm" type="{f4g/schemas/java/MetaModel}RPM"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HardDisk", propOrder = {
    "rpm"
})
public class HardDisk
    extends StorageUnit
    implements Cloneable, Visitable, CopyTo
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "int")
    protected RPM rpm;

    /**
     * Default no-arg constructor
     * 
     */
    public HardDisk() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public HardDisk(final String frameworkID, final StorageCapacity storageCapacity, final IoRate maxReadRate, final IoRate maxWriteRate, final IoRate readRate, final IoRate writeRate, final Power powerIdle, final Power powerMax, final Power computedPower, final List<Cache> cache, final QName jaxbElementName, final RPM rpm) {
        super(frameworkID, storageCapacity, maxReadRate, maxWriteRate, readRate, writeRate, powerIdle, powerMax, computedPower, cache, jaxbElementName);
        this.rpm = rpm;
    }

    /**
     * Gets the value of the rpm property.
     * 
     * @return
     *     possible object is
     *     {@link RPM }
     *     
     */
    public RPM getRpm() {
        return rpm;
    }

    /**
     * Sets the value of the rpm property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPM }
     *     
     */
    public void setRpm(RPM value) {
        this.rpm = value;
    }

    public void accept(Visitor aVisitor) {
        aVisitor.visit(this);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof HardDisk) {
            final HardDisk copy = ((HardDisk) draftCopy);
            if (this.rpm!= null) {
                RPM sourceRpm;
                sourceRpm = this.getRpm();
                RPM copyRpm = ((RPM) strategy.copy(LocatorUtils.property(locator, "rpm", sourceRpm), sourceRpm));
                copy.setRpm(copyRpm);
            } else {
                copy.rpm = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new HardDisk();
    }

}
