//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java.metamodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import com.massfords.humantask.Named;
import com.massfords.humantask.Visitable;
import com.massfords.humantask.Visitor;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for NetworkNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkNode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="processingBandwidth" type="{f4g/schemas/java/MetaModel}Bandwidth"/&gt;
 *         &lt;element name="status" type="{f4g/schemas/java/MetaModel}NetworkNodeStatus"/&gt;
 *         &lt;element name="powerIdle" type="{f4g/schemas/java/MetaModel}Power"/&gt;
 *         &lt;element name="powerMax" type="{f4g/schemas/java/MetaModel}Power"/&gt;
 *         &lt;element name="forwardFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="frameworkID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="computedPower" type="{f4g/schemas/java/MetaModel}Power" minOccurs="0"/&gt;
 *         &lt;element name="measuredPower" type="{f4g/schemas/java/MetaModel}Power" minOccurs="0"/&gt;
 *         &lt;element ref="{f4g/schemas/java/MetaModel}Fan" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{f4g/schemas/java/MetaModel}WaterCooler" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{f4g/schemas/java/MetaModel}PSU" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{f4g/schemas/java/MetaModel}NetworkPort" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="frameworkRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkNode", propOrder = {
    "processingBandwidth",
    "status",
    "powerIdle",
    "powerMax",
    "forwardFlag",
    "frameworkID",
    "computedPower",
    "measuredPower",
    "fan",
    "waterCooler",
    "psu",
    "networkPort"
})
@XmlSeeAlso({
    NIC.class,
    BoxNetwork.class,
    RackableNetwork.class
})
public class NetworkNode implements Cloneable, Named, Visitable, CopyTo
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "double")
    protected Bandwidth processingBandwidth;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NetworkNodeStatus status;
    @XmlElement(required = true)
    @XmlSchemaType(name = "double")
    protected Power powerIdle;
    @XmlElement(required = true)
    @XmlSchemaType(name = "double")
    protected Power powerMax;
    protected boolean forwardFlag;
    @XmlElement(required = true)
    protected String frameworkID;
    @XmlSchemaType(name = "double")
    protected Power computedPower;
    @XmlSchemaType(name = "double")
    protected Power measuredPower;
    @XmlElement(name = "Fan", namespace = "f4g/schemas/java/MetaModel")
    protected List<Fan> fan;
    @XmlElement(name = "WaterCooler", namespace = "f4g/schemas/java/MetaModel")
    protected List<WaterCooler> waterCooler;
    @XmlElement(name = "PSU", namespace = "f4g/schemas/java/MetaModel")
    protected List<PSU> psu;
    @XmlElement(name = "NetworkPort", namespace = "f4g/schemas/java/MetaModel")
    protected List<NetworkPort> networkPort;
    @XmlAttribute(name = "frameworkRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object frameworkRef;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlTransient
    private QName jaxbElementName;

    /**
     * Default no-arg constructor
     * 
     */
    public NetworkNode() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public NetworkNode(final Bandwidth processingBandwidth, final NetworkNodeStatus status, final Power powerIdle, final Power powerMax, final boolean forwardFlag, final String frameworkID, final Power computedPower, final Power measuredPower, final List<Fan> fan, final List<WaterCooler> waterCooler, final List<PSU> psu, final List<NetworkPort> networkPort, final Object frameworkRef, final String id, final QName jaxbElementName) {
        this.processingBandwidth = processingBandwidth;
        this.status = status;
        this.powerIdle = powerIdle;
        this.powerMax = powerMax;
        this.forwardFlag = forwardFlag;
        this.frameworkID = frameworkID;
        this.computedPower = computedPower;
        this.measuredPower = measuredPower;
        this.fan = fan;
        this.waterCooler = waterCooler;
        this.psu = psu;
        this.networkPort = networkPort;
        this.frameworkRef = frameworkRef;
        this.id = id;
        this.jaxbElementName = jaxbElementName;
    }

    /**
     * Gets the value of the processingBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Bandwidth }
     *     
     */
    public Bandwidth getProcessingBandwidth() {
        return processingBandwidth;
    }

    /**
     * Sets the value of the processingBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bandwidth }
     *     
     */
    public void setProcessingBandwidth(Bandwidth value) {
        this.processingBandwidth = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkNodeStatus }
     *     
     */
    public NetworkNodeStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkNodeStatus }
     *     
     */
    public void setStatus(NetworkNodeStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the powerIdle property.
     * 
     * @return
     *     possible object is
     *     {@link Power }
     *     
     */
    public Power getPowerIdle() {
        return powerIdle;
    }

    /**
     * Sets the value of the powerIdle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Power }
     *     
     */
    public void setPowerIdle(Power value) {
        this.powerIdle = value;
    }

    /**
     * Gets the value of the powerMax property.
     * 
     * @return
     *     possible object is
     *     {@link Power }
     *     
     */
    public Power getPowerMax() {
        return powerMax;
    }

    /**
     * Sets the value of the powerMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Power }
     *     
     */
    public void setPowerMax(Power value) {
        this.powerMax = value;
    }

    /**
     * Gets the value of the forwardFlag property.
     * 
     */
    public boolean isForwardFlag() {
        return forwardFlag;
    }

    /**
     * Sets the value of the forwardFlag property.
     * 
     */
    public void setForwardFlag(boolean value) {
        this.forwardFlag = value;
    }

    /**
     * Gets the value of the frameworkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameworkID() {
        return frameworkID;
    }

    /**
     * Sets the value of the frameworkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameworkID(String value) {
        this.frameworkID = value;
    }

    /**
     * Gets the value of the computedPower property.
     * 
     * @return
     *     possible object is
     *     {@link Power }
     *     
     */
    public Power getComputedPower() {
        return computedPower;
    }

    /**
     * Sets the value of the computedPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Power }
     *     
     */
    public void setComputedPower(Power value) {
        this.computedPower = value;
    }

    /**
     * Gets the value of the measuredPower property.
     * 
     * @return
     *     possible object is
     *     {@link Power }
     *     
     */
    public Power getMeasuredPower() {
        return measuredPower;
    }

    /**
     * Sets the value of the measuredPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Power }
     *     
     */
    public void setMeasuredPower(Power value) {
        this.measuredPower = value;
    }

    /**
     * Gets the value of the fan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fan }
     * 
     * 
     */
    public List<Fan> getFan() {
        if (fan == null) {
            fan = new ArrayList<Fan>();
        }
        return this.fan;
    }

    /**
     * Gets the value of the waterCooler property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waterCooler property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaterCooler().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaterCooler }
     * 
     * 
     */
    public List<WaterCooler> getWaterCooler() {
        if (waterCooler == null) {
            waterCooler = new ArrayList<WaterCooler>();
        }
        return this.waterCooler;
    }

    /**
     * Gets the value of the psu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the psu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPSU().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PSU }
     * 
     * 
     */
    public List<PSU> getPSU() {
        if (psu == null) {
            psu = new ArrayList<PSU>();
        }
        return this.psu;
    }

    /**
     * Gets the value of the networkPort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkPort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkPort }
     * 
     * 
     */
    public List<NetworkPort> getNetworkPort() {
        if (networkPort == null) {
            networkPort = new ArrayList<NetworkPort>();
        }
        return this.networkPort;
    }

    /**
     * Gets the value of the frameworkRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFrameworkRef() {
        return frameworkRef;
    }

    /**
     * Sets the value of the frameworkRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFrameworkRef(Object value) {
        this.frameworkRef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    public void setJAXBElementName(QName name) {
        this.jaxbElementName = name;
    }

    public QName getJAXBElementName() {
        return this.jaxbElementName;
    }

    public void afterUnmarshal(Unmarshaller u, Object parent) {
        if (parent instanceof JAXBElement) {
            this.jaxbElementName = ((JAXBElement) parent).getName();
        }
    }

    public void accept(Visitor aVisitor) {
        aVisitor.visit(this);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof NetworkNode) {
            final NetworkNode copy = ((NetworkNode) draftCopy);
            if (this.processingBandwidth!= null) {
                Bandwidth sourceProcessingBandwidth;
                sourceProcessingBandwidth = this.getProcessingBandwidth();
                Bandwidth copyProcessingBandwidth = ((Bandwidth) strategy.copy(LocatorUtils.property(locator, "processingBandwidth", sourceProcessingBandwidth), sourceProcessingBandwidth));
                copy.setProcessingBandwidth(copyProcessingBandwidth);
            } else {
                copy.processingBandwidth = null;
            }
            if (this.status!= null) {
                NetworkNodeStatus sourceStatus;
                sourceStatus = this.getStatus();
                NetworkNodeStatus copyStatus = ((NetworkNodeStatus) strategy.copy(LocatorUtils.property(locator, "status", sourceStatus), sourceStatus));
                copy.setStatus(copyStatus);
            } else {
                copy.status = null;
            }
            if (this.powerIdle!= null) {
                Power sourcePowerIdle;
                sourcePowerIdle = this.getPowerIdle();
                Power copyPowerIdle = ((Power) strategy.copy(LocatorUtils.property(locator, "powerIdle", sourcePowerIdle), sourcePowerIdle));
                copy.setPowerIdle(copyPowerIdle);
            } else {
                copy.powerIdle = null;
            }
            if (this.powerMax!= null) {
                Power sourcePowerMax;
                sourcePowerMax = this.getPowerMax();
                Power copyPowerMax = ((Power) strategy.copy(LocatorUtils.property(locator, "powerMax", sourcePowerMax), sourcePowerMax));
                copy.setPowerMax(copyPowerMax);
            } else {
                copy.powerMax = null;
            }
            boolean sourceForwardFlag;
            sourceForwardFlag = (true?this.isForwardFlag():false);
            boolean copyForwardFlag = strategy.copy(LocatorUtils.property(locator, "forwardFlag", sourceForwardFlag), sourceForwardFlag);
            copy.setForwardFlag(copyForwardFlag);
            if (this.frameworkID!= null) {
                String sourceFrameworkID;
                sourceFrameworkID = this.getFrameworkID();
                String copyFrameworkID = ((String) strategy.copy(LocatorUtils.property(locator, "frameworkID", sourceFrameworkID), sourceFrameworkID));
                copy.setFrameworkID(copyFrameworkID);
            } else {
                copy.frameworkID = null;
            }
            if (this.computedPower!= null) {
                Power sourceComputedPower;
                sourceComputedPower = this.getComputedPower();
                Power copyComputedPower = ((Power) strategy.copy(LocatorUtils.property(locator, "computedPower", sourceComputedPower), sourceComputedPower));
                copy.setComputedPower(copyComputedPower);
            } else {
                copy.computedPower = null;
            }
            if (this.measuredPower!= null) {
                Power sourceMeasuredPower;
                sourceMeasuredPower = this.getMeasuredPower();
                Power copyMeasuredPower = ((Power) strategy.copy(LocatorUtils.property(locator, "measuredPower", sourceMeasuredPower), sourceMeasuredPower));
                copy.setMeasuredPower(copyMeasuredPower);
            } else {
                copy.measuredPower = null;
            }
            if ((this.fan!= null)&&(!this.fan.isEmpty())) {
                List<Fan> sourceFan;
                sourceFan = (((this.fan!= null)&&(!this.fan.isEmpty()))?this.getFan():null);
                @SuppressWarnings("unchecked")
                List<Fan> copyFan = ((List<Fan> ) strategy.copy(LocatorUtils.property(locator, "fan", sourceFan), sourceFan));
                copy.fan = null;
                if (copyFan!= null) {
                    List<Fan> uniqueFanl = copy.getFan();
                    uniqueFanl.addAll(copyFan);
                }
            } else {
                copy.fan = null;
            }
            if ((this.waterCooler!= null)&&(!this.waterCooler.isEmpty())) {
                List<WaterCooler> sourceWaterCooler;
                sourceWaterCooler = (((this.waterCooler!= null)&&(!this.waterCooler.isEmpty()))?this.getWaterCooler():null);
                @SuppressWarnings("unchecked")
                List<WaterCooler> copyWaterCooler = ((List<WaterCooler> ) strategy.copy(LocatorUtils.property(locator, "waterCooler", sourceWaterCooler), sourceWaterCooler));
                copy.waterCooler = null;
                if (copyWaterCooler!= null) {
                    List<WaterCooler> uniqueWaterCoolerl = copy.getWaterCooler();
                    uniqueWaterCoolerl.addAll(copyWaterCooler);
                }
            } else {
                copy.waterCooler = null;
            }
            if ((this.psu!= null)&&(!this.psu.isEmpty())) {
                List<PSU> sourcePSU;
                sourcePSU = (((this.psu!= null)&&(!this.psu.isEmpty()))?this.getPSU():null);
                @SuppressWarnings("unchecked")
                List<PSU> copyPSU = ((List<PSU> ) strategy.copy(LocatorUtils.property(locator, "psu", sourcePSU), sourcePSU));
                copy.psu = null;
                if (copyPSU!= null) {
                    List<PSU> uniquePSUl = copy.getPSU();
                    uniquePSUl.addAll(copyPSU);
                }
            } else {
                copy.psu = null;
            }
            if ((this.networkPort!= null)&&(!this.networkPort.isEmpty())) {
                List<NetworkPort> sourceNetworkPort;
                sourceNetworkPort = (((this.networkPort!= null)&&(!this.networkPort.isEmpty()))?this.getNetworkPort():null);
                @SuppressWarnings("unchecked")
                List<NetworkPort> copyNetworkPort = ((List<NetworkPort> ) strategy.copy(LocatorUtils.property(locator, "networkPort", sourceNetworkPort), sourceNetworkPort));
                copy.networkPort = null;
                if (copyNetworkPort!= null) {
                    List<NetworkPort> uniqueNetworkPortl = copy.getNetworkPort();
                    uniqueNetworkPortl.addAll(copyNetworkPort);
                }
            } else {
                copy.networkPort = null;
            }
            if (this.frameworkRef!= null) {
                Object sourceFrameworkRef;
                sourceFrameworkRef = this.getFrameworkRef();
                Object copyFrameworkRef = ((Object) strategy.copy(LocatorUtils.property(locator, "frameworkRef", sourceFrameworkRef), sourceFrameworkRef));
                copy.setFrameworkRef(copyFrameworkRef);
            } else {
                copy.frameworkRef = null;
            }
            if (this.id!= null) {
                String sourceID;
                sourceID = this.getID();
                String copyID = ((String) strategy.copy(LocatorUtils.property(locator, "id", sourceID), sourceID));
                copy.setID(copyID);
            } else {
                copy.id = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new NetworkNode();
    }

}
