//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import com.massfords.humantask.Visitable;
import com.massfords.humantask.Visitor;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ENTITIES simple type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;simpleType name="ENTITIES"&gt;
 *   &lt;restriction&gt;
 *     &lt;simpleType&gt;
 *       &lt;list itemType="{http://www.w3.org/2001/XMLSchema}ENTITY" /&gt;
 *     &lt;/simpleType&gt;
 *     &lt;minLength value="1"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ENTITIES", propOrder = {
    "value"
})
public class ENTITIES implements Cloneable, Visitable, CopyTo
{

    @XmlValue
    @XmlSchemaType(name = "ENTITIES")
    protected List<ENTITY> value;

    /**
     * Default no-arg constructor
     * 
     */
    public ENTITIES() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public ENTITIES(final List<ENTITY> value) {
        this.value = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ENTITY }
     * 
     * 
     */
    public List<ENTITY> getValue() {
        if (value == null) {
            value = new ArrayList<ENTITY>();
        }
        return this.value;
    }

    public void accept(Visitor aVisitor) {
        aVisitor.visit(this);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof ENTITIES) {
            final ENTITIES copy = ((ENTITIES) draftCopy);
            if ((this.value!= null)&&(!this.value.isEmpty())) {
                List<ENTITY> sourceValue;
                sourceValue = (((this.value!= null)&&(!this.value.isEmpty()))?this.getValue():null);
                @SuppressWarnings("unchecked")
                List<ENTITY> copyValue = ((List<ENTITY> ) strategy.copy(LocatorUtils.property(locator, "value", sourceValue), sourceValue));
                copy.value = null;
                if (copyValue!= null) {
                    List<ENTITY> uniqueValuel = copy.getValue();
                    uniqueValuel.addAll(copyValue);
                }
            } else {
                copy.value = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new ENTITIES();
    }

}
