//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java.constraints.optimizerconstraints;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.massfords.humantask.Visitable;
import com.massfords.humantask.Visitor;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for boundedSLAsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boundedSLAsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SLA" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="idref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boundedSLAsType", propOrder = {
    "sla"
})
public class BoundedSLAsType implements Cloneable, Visitable, CopyTo
{

    @XmlElement(name = "SLA", required = true)
    protected List<BoundedSLAsType.SLA> sla;

    /**
     * Default no-arg constructor
     * 
     */
    public BoundedSLAsType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public BoundedSLAsType(final List<BoundedSLAsType.SLA> sla) {
        this.sla = sla;
    }

    /**
     * Gets the value of the sla property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sla property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSLA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoundedSLAsType.SLA }
     * 
     * 
     */
    public List<BoundedSLAsType.SLA> getSLA() {
        if (sla == null) {
            sla = new ArrayList<BoundedSLAsType.SLA>();
        }
        return this.sla;
    }

    public void accept(Visitor aVisitor) {
        aVisitor.visit(this);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof BoundedSLAsType) {
            final BoundedSLAsType copy = ((BoundedSLAsType) draftCopy);
            if ((this.sla!= null)&&(!this.sla.isEmpty())) {
                List<BoundedSLAsType.SLA> sourceSLA;
                sourceSLA = (((this.sla!= null)&&(!this.sla.isEmpty()))?this.getSLA():null);
                @SuppressWarnings("unchecked")
                List<BoundedSLAsType.SLA> copySLA = ((List<BoundedSLAsType.SLA> ) strategy.copy(LocatorUtils.property(locator, "sla", sourceSLA), sourceSLA));
                copy.sla = null;
                if (copySLA!= null) {
                    List<BoundedSLAsType.SLA> uniqueSLAl = copy.getSLA();
                    uniqueSLAl.addAll(copySLA);
                }
            } else {
                copy.sla = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new BoundedSLAsType();
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="idref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SLA implements Cloneable, Visitable, CopyTo
    {

        @XmlAttribute(name = "idref", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected SLAType.SLA idref;

        /**
         * Default no-arg constructor
         * 
         */
        public SLA() {
            super();
        }

        /**
         * Fully-initialising value constructor
         * 
         */
        public SLA(final SLAType.SLA idref) {
            this.idref = idref;
        }

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public SLAType.SLA getIdref() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIdref(SLAType.SLA value) {
            this.idref = value;
        }

        public void accept(Visitor aVisitor) {
            aVisitor.visit(this);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof BoundedSLAsType.SLA) {
                final BoundedSLAsType.SLA copy = ((BoundedSLAsType.SLA) draftCopy);
                if (this.idref!= null) {
                    SLAType.SLA sourceIdref;
                    sourceIdref = this.getIdref();
                    SLAType.SLA copyIdref = ((SLAType.SLA) strategy.copy(LocatorUtils.property(locator, "idref", sourceIdref), sourceIdref));
                    copy.setIdref(copyIdref);
                } else {
                    copy.idref = null;
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new BoundedSLAsType.SLA();
        }

    }

}
