//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java.constraints.optimizerconstraints;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.massfords.humantask.Visitable;
import com.massfords.humantask.Visitor;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for boundedPoliciesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boundedPoliciesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Policy" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="idref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boundedPoliciesType", propOrder = {
    "policy"
})
public class BoundedPoliciesType implements Cloneable, Visitable, CopyTo
{

    @XmlElement(name = "Policy", required = true)
    protected List<BoundedPoliciesType.Policy> policy;

    /**
     * Default no-arg constructor
     * 
     */
    public BoundedPoliciesType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public BoundedPoliciesType(final List<BoundedPoliciesType.Policy> policy) {
        this.policy = policy;
    }

    /**
     * Gets the value of the policy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoundedPoliciesType.Policy }
     * 
     * 
     */
    public List<BoundedPoliciesType.Policy> getPolicy() {
        if (policy == null) {
            policy = new ArrayList<BoundedPoliciesType.Policy>();
        }
        return this.policy;
    }

    public void accept(Visitor aVisitor) {
        aVisitor.visit(this);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof BoundedPoliciesType) {
            final BoundedPoliciesType copy = ((BoundedPoliciesType) draftCopy);
            if ((this.policy!= null)&&(!this.policy.isEmpty())) {
                List<BoundedPoliciesType.Policy> sourcePolicy;
                sourcePolicy = (((this.policy!= null)&&(!this.policy.isEmpty()))?this.getPolicy():null);
                @SuppressWarnings("unchecked")
                List<BoundedPoliciesType.Policy> copyPolicy = ((List<BoundedPoliciesType.Policy> ) strategy.copy(LocatorUtils.property(locator, "policy", sourcePolicy), sourcePolicy));
                copy.policy = null;
                if (copyPolicy!= null) {
                    List<BoundedPoliciesType.Policy> uniquePolicyl = copy.getPolicy();
                    uniquePolicyl.addAll(copyPolicy);
                }
            } else {
                copy.policy = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new BoundedPoliciesType();
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="idref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Policy implements Cloneable, Visitable, CopyTo
    {

        @XmlAttribute(name = "idref", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected PolicyType.Policy idref;

        /**
         * Default no-arg constructor
         * 
         */
        public Policy() {
            super();
        }

        /**
         * Fully-initialising value constructor
         * 
         */
        public Policy(final PolicyType.Policy idref) {
            this.idref = idref;
        }

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public PolicyType.Policy getIdref() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIdref(PolicyType.Policy value) {
            this.idref = value;
        }

        public void accept(Visitor aVisitor) {
            aVisitor.visit(this);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof BoundedPoliciesType.Policy) {
                final BoundedPoliciesType.Policy copy = ((BoundedPoliciesType.Policy) draftCopy);
                if (this.idref!= null) {
                    PolicyType.Policy sourceIdref;
                    sourceIdref = this.getIdref();
                    PolicyType.Policy copyIdref = ((PolicyType.Policy) strategy.copy(LocatorUtils.property(locator, "idref", sourceIdref), sourceIdref));
                    copy.setIdref(copyIdref);
                } else {
                    copy.idref = null;
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new BoundedPoliciesType.Policy();
        }

    }

}
