//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.actions;

import java.metamodel.PowerType;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ActionRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IsAutomatic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OperatorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ComputedPowerBefore" type="{java/MetaModel}PowerType" minOccurs="0"/>
 *         &lt;element name="ComputedPowerAfter" type="{java/MetaModel}PowerType" minOccurs="0"/>
 *         &lt;element name="ActionList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{java/Actions}Action" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionRequestType", propOrder = {
    "datetime",
    "isAutomatic",
    "operatorName",
    "computedPowerBefore",
    "computedPowerAfter",
    "actionList"
})
public class ActionRequestType {

    @XmlElement(name = "Datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datetime;
    @XmlElement(name = "IsAutomatic")
    protected Boolean isAutomatic;
    @XmlElement(name = "OperatorName")
    protected String operatorName;
    @XmlElement(name = "ComputedPowerBefore")
    protected PowerType computedPowerBefore;
    @XmlElement(name = "ComputedPowerAfter")
    protected PowerType computedPowerAfter;
    @XmlElement(name = "ActionList", required = true)
    protected ActionRequestType.ActionList actionList;

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetime(XMLGregorianCalendar value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the isAutomatic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAutomatic() {
        return isAutomatic;
    }

    /**
     * Sets the value of the isAutomatic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAutomatic(Boolean value) {
        this.isAutomatic = value;
    }

    /**
     * Gets the value of the operatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * Sets the value of the operatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorName(String value) {
        this.operatorName = value;
    }

    /**
     * Gets the value of the computedPowerBefore property.
     * 
     * @return
     *     possible object is
     *     {@link PowerType }
     *     
     */
    public PowerType getComputedPowerBefore() {
        return computedPowerBefore;
    }

    /**
     * Sets the value of the computedPowerBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerType }
     *     
     */
    public void setComputedPowerBefore(PowerType value) {
        this.computedPowerBefore = value;
    }

    /**
     * Gets the value of the computedPowerAfter property.
     * 
     * @return
     *     possible object is
     *     {@link PowerType }
     *     
     */
    public PowerType getComputedPowerAfter() {
        return computedPowerAfter;
    }

    /**
     * Sets the value of the computedPowerAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerType }
     *     
     */
    public void setComputedPowerAfter(PowerType value) {
        this.computedPowerAfter = value;
    }

    /**
     * Gets the value of the actionList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionRequestType.ActionList }
     *     
     */
    public ActionRequestType.ActionList getActionList() {
        return actionList;
    }

    /**
     * Sets the value of the actionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionRequestType.ActionList }
     *     
     */
    public void setActionList(ActionRequestType.ActionList value) {
        this.actionList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{java/Actions}Action" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "action"
    })
    public static class ActionList {

        @XmlElementRef(name = "Action", namespace = "java/Actions", type = JAXBElement.class)
        protected List<JAXBElement<? extends AbstractBaseActionType>> action;

        /**
         * Gets the value of the action property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the action property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link PowerOffActionType }{@code >}
         * {@link JAXBElement }{@code <}{@link StandByActionType }{@code >}
         * {@link JAXBElement }{@code <}{@link LiveMigrateVMActionType }{@code >}
         * {@link JAXBElement }{@code <}{@link StartJobActionType }{@code >}
         * {@link JAXBElement }{@code <}{@link AbstractBaseActionType }{@code >}
         * {@link JAXBElement }{@code <}{@link MoveVMActionType }{@code >}
         * {@link JAXBElement }{@code <}{@link PowerOnActionType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<? extends AbstractBaseActionType>> getAction() {
            if (action == null) {
                action = new ArrayList<JAXBElement<? extends AbstractBaseActionType>>();
            }
            return this.action;
        }

    }

}
