//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.actions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the java.actions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StandBy_QNAME = new QName("java/Actions", "StandBy");
    private final static QName _ActionRequest_QNAME = new QName("java/Actions", "ActionRequest");
    private final static QName _MoveVM_QNAME = new QName("java/Actions", "MoveVM");
    private final static QName _Action_QNAME = new QName("java/Actions", "Action");
    private final static QName _StartJob_QNAME = new QName("java/Actions", "StartJob");
    private final static QName _PowerOff_QNAME = new QName("java/Actions", "PowerOff");
    private final static QName _LiveMigrateVM_QNAME = new QName("java/Actions", "LiveMigrateVM");
    private final static QName _PowerOn_QNAME = new QName("java/Actions", "PowerOn");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: java.actions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PowerOnActionType }
     * 
     */
    public PowerOnActionType createPowerOnActionType() {
        return new PowerOnActionType();
    }

    /**
     * Create an instance of {@link LiveMigrateVMActionType }
     * 
     */
    public LiveMigrateVMActionType createLiveMigrateVMActionType() {
        return new LiveMigrateVMActionType();
    }

    /**
     * Create an instance of {@link ActionRequestType.ActionList }
     * 
     */
    public ActionRequestType.ActionList createActionRequestTypeActionList() {
        return new ActionRequestType.ActionList();
    }

    /**
     * Create an instance of {@link MoveVMActionType }
     * 
     */
    public MoveVMActionType createMoveVMActionType() {
        return new MoveVMActionType();
    }

    /**
     * Create an instance of {@link StartJobActionType }
     * 
     */
    public StartJobActionType createStartJobActionType() {
        return new StartJobActionType();
    }

    /**
     * Create an instance of {@link PowerOffActionType }
     * 
     */
    public PowerOffActionType createPowerOffActionType() {
        return new PowerOffActionType();
    }

    /**
     * Create an instance of {@link StandByActionType }
     * 
     */
    public StandByActionType createStandByActionType() {
        return new StandByActionType();
    }

    /**
     * Create an instance of {@link ActionRequestType }
     * 
     */
    public ActionRequestType createActionRequestType() {
        return new ActionRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandByActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "StandBy", substitutionHeadNamespace = "java/Actions", substitutionHeadName = "Action")
    public JAXBElement<StandByActionType> createStandBy(StandByActionType value) {
        return new JAXBElement<StandByActionType>(_StandBy_QNAME, StandByActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "ActionRequest")
    public JAXBElement<ActionRequestType> createActionRequest(ActionRequestType value) {
        return new JAXBElement<ActionRequestType>(_ActionRequest_QNAME, ActionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MoveVMActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "MoveVM", substitutionHeadNamespace = "java/Actions", substitutionHeadName = "Action")
    public JAXBElement<MoveVMActionType> createMoveVM(MoveVMActionType value) {
        return new JAXBElement<MoveVMActionType>(_MoveVM_QNAME, MoveVMActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractBaseActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "Action")
    public JAXBElement<AbstractBaseActionType> createAction(AbstractBaseActionType value) {
        return new JAXBElement<AbstractBaseActionType>(_Action_QNAME, AbstractBaseActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartJobActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "StartJob", substitutionHeadNamespace = "java/Actions", substitutionHeadName = "Action")
    public JAXBElement<StartJobActionType> createStartJob(StartJobActionType value) {
        return new JAXBElement<StartJobActionType>(_StartJob_QNAME, StartJobActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerOffActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "PowerOff", substitutionHeadNamespace = "java/Actions", substitutionHeadName = "Action")
    public JAXBElement<PowerOffActionType> createPowerOff(PowerOffActionType value) {
        return new JAXBElement<PowerOffActionType>(_PowerOff_QNAME, PowerOffActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LiveMigrateVMActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "LiveMigrateVM", substitutionHeadNamespace = "java/Actions", substitutionHeadName = "Action")
    public JAXBElement<LiveMigrateVMActionType> createLiveMigrateVM(LiveMigrateVMActionType value) {
        return new JAXBElement<LiveMigrateVMActionType>(_LiveMigrateVM_QNAME, LiveMigrateVMActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerOnActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java/Actions", name = "PowerOn", substitutionHeadNamespace = "java/Actions", substitutionHeadName = "Action")
    public JAXBElement<PowerOnActionType> createPowerOn(PowerOnActionType value) {
        return new JAXBElement<PowerOnActionType>(_PowerOn_QNAME, PowerOnActionType.class, null, value);
    }

}
