//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.metamodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NativeOperatingSystemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NativeOperatingSystemType">
 *   &lt;complexContent>
 *     &lt;extension base="{java/MetaModel}OperatingSystemType">
 *       &lt;sequence>
 *         &lt;element ref="{java/MetaModel}SoftwareApplication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{java/MetaModel}ClusterManagement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{java/MetaModel}Node" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{java/MetaModel}HostedHypervisor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NativeOperatingSystemType", propOrder = {
    "softwareApplication",
    "clusterManagement",
    "node",
    "hostedHypervisor"
})
public class NativeOperatingSystemType
    extends OperatingSystemType
{

    @XmlElement(name = "SoftwareApplication", namespace = "java/MetaModel")
    protected List<SoftwareApplicationType> softwareApplication;
    @XmlElement(name = "ClusterManagement", namespace = "java/MetaModel")
    protected List<ClusterManagementType> clusterManagement;
    @XmlElement(name = "Node", namespace = "java/MetaModel")
    protected List<NodeType> node;
    @XmlElement(name = "HostedHypervisor", namespace = "java/MetaModel")
    protected List<HostedHypervisorType> hostedHypervisor;

    /**
     * Gets the value of the softwareApplication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the softwareApplication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoftwareApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareApplicationType }
     * 
     * 
     */
    public List<SoftwareApplicationType> getSoftwareApplication() {
        if (softwareApplication == null) {
            softwareApplication = new ArrayList<SoftwareApplicationType>();
        }
        return this.softwareApplication;
    }

    /**
     * Gets the value of the clusterManagement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clusterManagement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClusterManagement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClusterManagementType }
     * 
     * 
     */
    public List<ClusterManagementType> getClusterManagement() {
        if (clusterManagement == null) {
            clusterManagement = new ArrayList<ClusterManagementType>();
        }
        return this.clusterManagement;
    }

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeType }
     * 
     * 
     */
    public List<NodeType> getNode() {
        if (node == null) {
            node = new ArrayList<NodeType>();
        }
        return this.node;
    }

    /**
     * Gets the value of the hostedHypervisor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostedHypervisor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostedHypervisor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HostedHypervisorType }
     * 
     * 
     */
    public List<HostedHypervisorType> getHostedHypervisor() {
        if (hostedHypervisor == null) {
            hostedHypervisor = new ArrayList<HostedHypervisorType>();
        }
        return this.hostedHypervisor;
    }

}
