//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.metamodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="priority" type="{java/MetaModel}QueuePriorityType"/>
 *         &lt;element name="possibleProperties" type="{java/MetaModel}QueuePossiblePropType" maxOccurs="unbounded"/>
 *         &lt;element name="forcedProperties" type="{java/MetaModel}QueueForcedPropType" maxOccurs="unbounded"/>
 *         &lt;element name="wallTimeLimit" type="{java/MetaModel}JobLimitType"/>
 *         &lt;element name="numberOfNodesLimit" type="{java/MetaModel}JobLimitType"/>
 *         &lt;element name="jobs" type="{java/MetaModel}JobType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueueType", propOrder = {
    "priority",
    "possibleProperties",
    "forcedProperties",
    "wallTimeLimit",
    "numberOfNodesLimit",
    "jobs"
})
public class QueueType {

    @XmlElement(required = true)
    protected QueuePriorityType priority;
    @XmlElement(required = true)
    protected List<QueuePossiblePropType> possibleProperties;
    @XmlElement(required = true)
    protected List<QueueForcedPropType> forcedProperties;
    @XmlElement(required = true)
    protected JobLimitType wallTimeLimit;
    @XmlElement(required = true)
    protected JobLimitType numberOfNodesLimit;
    protected List<JobType> jobs;

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link QueuePriorityType }
     *     
     */
    public QueuePriorityType getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueuePriorityType }
     *     
     */
    public void setPriority(QueuePriorityType value) {
        this.priority = value;
    }

    /**
     * Gets the value of the possibleProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the possibleProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPossibleProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueuePossiblePropType }
     * 
     * 
     */
    public List<QueuePossiblePropType> getPossibleProperties() {
        if (possibleProperties == null) {
            possibleProperties = new ArrayList<QueuePossiblePropType>();
        }
        return this.possibleProperties;
    }

    /**
     * Gets the value of the forcedProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forcedProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForcedProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueueForcedPropType }
     * 
     * 
     */
    public List<QueueForcedPropType> getForcedProperties() {
        if (forcedProperties == null) {
            forcedProperties = new ArrayList<QueueForcedPropType>();
        }
        return this.forcedProperties;
    }

    /**
     * Gets the value of the wallTimeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JobLimitType }
     *     
     */
    public JobLimitType getWallTimeLimit() {
        return wallTimeLimit;
    }

    /**
     * Sets the value of the wallTimeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobLimitType }
     *     
     */
    public void setWallTimeLimit(JobLimitType value) {
        this.wallTimeLimit = value;
    }

    /**
     * Gets the value of the numberOfNodesLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JobLimitType }
     *     
     */
    public JobLimitType getNumberOfNodesLimit() {
        return numberOfNodesLimit;
    }

    /**
     * Sets the value of the numberOfNodesLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobLimitType }
     *     
     */
    public void setNumberOfNodesLimit(JobLimitType value) {
        this.numberOfNodesLimit = value;
    }

    /**
     * Gets the value of the jobs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobType }
     * 
     * 
     */
    public List<JobType> getJobs() {
        if (jobs == null) {
            jobs = new ArrayList<JobType>();
        }
        return this.jobs;
    }

}
