//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.metamodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueueForcedPropType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QueueForcedPropType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TO_BE_REVISED"/>
 *     &lt;enumeration value="PROP2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QueueForcedPropType")
@XmlEnum
public enum QueueForcedPropType {

    TO_BE_REVISED("TO_BE_REVISED"),
    @XmlEnumValue("PROP2")
    PROP_2("PROP2");
    private final String value;

    QueueForcedPropType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QueueForcedPropType fromValue(String v) {
        for (QueueForcedPropType c: QueueForcedPropType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
