//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 04:51:12 PM CEST 
//


package java.metamodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RAMTypeVendorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RAMTypeVendorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KINGSTON"/>
 *     &lt;enumeration value="SAMSUNG"/>
 *     &lt;enumeration value="HYNIX"/>
 *     &lt;enumeration value="GENERIC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RAMTypeVendorType")
@XmlEnum
public enum RAMTypeVendorType {

    KINGSTON,
    SAMSUNG,
    HYNIX,
    GENERIC;

    public String value() {
        return name();
    }

    public static RAMTypeVendorType fromValue(String v) {
        return valueOf(v);
    }

}
