//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.metamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VirtualMachineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualMachineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfCPUs" type="{java/MetaModel}NrOfCpusType" minOccurs="0"/>
 *         &lt;element name="actualCPUUsage" type="{java/MetaModel}CpuUsageType" minOccurs="0"/>
 *         &lt;element name="actualStorageUsage" type="{java/MetaModel}StorageUsageType" minOccurs="0"/>
 *         &lt;element name="actualDiskIORate" type="{java/MetaModel}IoRateType" minOccurs="0"/>
 *         &lt;element name="actualMemoryUsage" type="{java/MetaModel}MemoryUsageType" minOccurs="0"/>
 *         &lt;element name="actualNetworkUsage" type="{java/MetaModel}NetworkUsageType" minOccurs="0"/>
 *         &lt;element ref="{java/MetaModel}HostedOperatingSystem" minOccurs="0"/>
 *         &lt;element name="frameworkID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cloudVmImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cloudVmType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="endTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lastMigrationTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="frameworkRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualMachineType", propOrder = {
    "name",
    "numberOfCPUs",
    "actualCPUUsage",
    "actualStorageUsage",
    "actualDiskIORate",
    "actualMemoryUsage",
    "actualNetworkUsage",
    "hostedOperatingSystem",
    "frameworkID",
    "cloudVmImage",
    "cloudVmType",
    "startTimestamp",
    "endTimestamp",
    "lastMigrationTimestamp"
})
public class VirtualMachineType {

    protected String name;
    protected NrOfCpusType numberOfCPUs;
    protected CpuUsageType actualCPUUsage;
    protected StorageUsageType actualStorageUsage;
    protected IoRateType actualDiskIORate;
    protected MemoryUsageType actualMemoryUsage;
    protected NetworkUsageType actualNetworkUsage;
    @XmlElement(name = "HostedOperatingSystem", namespace = "java/MetaModel")
    protected HostedOperatingSystemType hostedOperatingSystem;
    @XmlElement(required = true)
    protected String frameworkID;
    protected String cloudVmImage;
    protected String cloudVmType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimestamp;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTimestamp;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastMigrationTimestamp;
    @XmlAttribute(name = "frameworkRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object frameworkRef;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the numberOfCPUs property.
     * 
     * @return
     *     possible object is
     *     {@link NrOfCpusType }
     *     
     */
    public NrOfCpusType getNumberOfCPUs() {
        return numberOfCPUs;
    }

    /**
     * Sets the value of the numberOfCPUs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NrOfCpusType }
     *     
     */
    public void setNumberOfCPUs(NrOfCpusType value) {
        this.numberOfCPUs = value;
    }

    /**
     * Gets the value of the actualCPUUsage property.
     * 
     * @return
     *     possible object is
     *     {@link CpuUsageType }
     *     
     */
    public CpuUsageType getActualCPUUsage() {
        return actualCPUUsage;
    }

    /**
     * Sets the value of the actualCPUUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CpuUsageType }
     *     
     */
    public void setActualCPUUsage(CpuUsageType value) {
        this.actualCPUUsage = value;
    }

    /**
     * Gets the value of the actualStorageUsage property.
     * 
     * @return
     *     possible object is
     *     {@link StorageUsageType }
     *     
     */
    public StorageUsageType getActualStorageUsage() {
        return actualStorageUsage;
    }

    /**
     * Sets the value of the actualStorageUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageUsageType }
     *     
     */
    public void setActualStorageUsage(StorageUsageType value) {
        this.actualStorageUsage = value;
    }

    /**
     * Gets the value of the actualDiskIORate property.
     * 
     * @return
     *     possible object is
     *     {@link IoRateType }
     *     
     */
    public IoRateType getActualDiskIORate() {
        return actualDiskIORate;
    }

    /**
     * Sets the value of the actualDiskIORate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IoRateType }
     *     
     */
    public void setActualDiskIORate(IoRateType value) {
        this.actualDiskIORate = value;
    }

    /**
     * Gets the value of the actualMemoryUsage property.
     * 
     * @return
     *     possible object is
     *     {@link MemoryUsageType }
     *     
     */
    public MemoryUsageType getActualMemoryUsage() {
        return actualMemoryUsage;
    }

    /**
     * Sets the value of the actualMemoryUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemoryUsageType }
     *     
     */
    public void setActualMemoryUsage(MemoryUsageType value) {
        this.actualMemoryUsage = value;
    }

    /**
     * Gets the value of the actualNetworkUsage property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkUsageType }
     *     
     */
    public NetworkUsageType getActualNetworkUsage() {
        return actualNetworkUsage;
    }

    /**
     * Sets the value of the actualNetworkUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkUsageType }
     *     
     */
    public void setActualNetworkUsage(NetworkUsageType value) {
        this.actualNetworkUsage = value;
    }

    /**
     * Gets the value of the hostedOperatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link HostedOperatingSystemType }
     *     
     */
    public HostedOperatingSystemType getHostedOperatingSystem() {
        return hostedOperatingSystem;
    }

    /**
     * Sets the value of the hostedOperatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostedOperatingSystemType }
     *     
     */
    public void setHostedOperatingSystem(HostedOperatingSystemType value) {
        this.hostedOperatingSystem = value;
    }

    /**
     * Gets the value of the frameworkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameworkID() {
        return frameworkID;
    }

    /**
     * Sets the value of the frameworkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameworkID(String value) {
        this.frameworkID = value;
    }

    /**
     * Gets the value of the cloudVmImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudVmImage() {
        return cloudVmImage;
    }

    /**
     * Sets the value of the cloudVmImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudVmImage(String value) {
        this.cloudVmImage = value;
    }

    /**
     * Gets the value of the cloudVmType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudVmType() {
        return cloudVmType;
    }

    /**
     * Sets the value of the cloudVmType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudVmType(String value) {
        this.cloudVmType = value;
    }

    /**
     * Gets the value of the startTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * Sets the value of the startTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimestamp(XMLGregorianCalendar value) {
        this.startTimestamp = value;
    }

    /**
     * Gets the value of the endTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimestamp() {
        return endTimestamp;
    }

    /**
     * Sets the value of the endTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimestamp(XMLGregorianCalendar value) {
        this.endTimestamp = value;
    }

    /**
     * Gets the value of the lastMigrationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastMigrationTimestamp() {
        return lastMigrationTimestamp;
    }

    /**
     * Sets the value of the lastMigrationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastMigrationTimestamp(XMLGregorianCalendar value) {
        this.lastMigrationTimestamp = value;
    }

    /**
     * Gets the value of the frameworkRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFrameworkRef() {
        return frameworkRef;
    }

    /**
     * Sets the value of the frameworkRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFrameworkRef(Object value) {
        this.frameworkRef = value;
    }

}
