//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 04:51:12 PM CEST 
//


package java.metamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VMActionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VMActionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interLiveMigrate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="intraLiveMigrate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="interMoveVM" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="intraMoveVM" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VMActionsType", propOrder = {
    "interLiveMigrate",
    "intraLiveMigrate",
    "interMoveVM",
    "intraMoveVM"
})
public class VMActionsType {

    protected boolean interLiveMigrate;
    protected boolean intraLiveMigrate;
    protected boolean interMoveVM;
    protected boolean intraMoveVM;

    /**
     * Gets the value of the interLiveMigrate property.
     * 
     */
    public boolean isInterLiveMigrate() {
        return interLiveMigrate;
    }

    /**
     * Sets the value of the interLiveMigrate property.
     * 
     */
    public void setInterLiveMigrate(boolean value) {
        this.interLiveMigrate = value;
    }

    /**
     * Gets the value of the intraLiveMigrate property.
     * 
     */
    public boolean isIntraLiveMigrate() {
        return intraLiveMigrate;
    }

    /**
     * Sets the value of the intraLiveMigrate property.
     * 
     */
    public void setIntraLiveMigrate(boolean value) {
        this.intraLiveMigrate = value;
    }

    /**
     * Gets the value of the interMoveVM property.
     * 
     */
    public boolean isInterMoveVM() {
        return interMoveVM;
    }

    /**
     * Sets the value of the interMoveVM property.
     * 
     */
    public void setInterMoveVM(boolean value) {
        this.interMoveVM = value;
    }

    /**
     * Gets the value of the intraMoveVM property.
     * 
     */
    public boolean isIntraMoveVM() {
        return intraMoveVM;
    }

    /**
     * Sets the value of the intraMoveVM property.
     * 
     */
    public void setIntraMoveVM(boolean value) {
        this.intraMoveVM = value;
    }

}
