//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//


package f4g.schemas.java.actions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the f4g.schemas.java.actions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ActionRequest_QNAME = new QName("f4g/schemas/java/Actions", "ActionRequest");
    private final static QName _Action_QNAME = new QName("f4g/schemas/java/Actions", "Action");
    private final static QName _PowerOn_QNAME = new QName("f4g/schemas/java/Actions", "PowerOn");
    private final static QName _PowerOff_QNAME = new QName("f4g/schemas/java/Actions", "PowerOff");
    private final static QName _StandBy_QNAME = new QName("f4g/schemas/java/Actions", "StandBy");
    private final static QName _StartJob_QNAME = new QName("f4g/schemas/java/Actions", "StartJob");
    private final static QName _MoveVM_QNAME = new QName("f4g/schemas/java/Actions", "MoveVM");
    private final static QName _LiveMigrateVM_QNAME = new QName("f4g/schemas/java/Actions", "LiveMigrateVM");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: f4g.schemas.java.actions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActionRequest }
     * 
     */
    public ActionRequest createActionRequest() {
        return new ActionRequest();
    }

    /**
     * Create an instance of {@link PowerOnAction }
     * 
     */
    public PowerOnAction createPowerOnAction() {
        return new PowerOnAction();
    }

    /**
     * Create an instance of {@link PowerOffAction }
     * 
     */
    public PowerOffAction createPowerOffAction() {
        return new PowerOffAction();
    }

    /**
     * Create an instance of {@link StandByAction }
     * 
     */
    public StandByAction createStandByAction() {
        return new StandByAction();
    }

    /**
     * Create an instance of {@link StartJobAction }
     * 
     */
    public StartJobAction createStartJobAction() {
        return new StartJobAction();
    }

    /**
     * Create an instance of {@link MoveVMAction }
     * 
     */
    public MoveVMAction createMoveVMAction() {
        return new MoveVMAction();
    }

    /**
     * Create an instance of {@link LiveMigrateVMAction }
     * 
     */
    public LiveMigrateVMAction createLiveMigrateVMAction() {
        return new LiveMigrateVMAction();
    }

    /**
     * Create an instance of {@link ActionRequest.ActionList }
     * 
     */
    public ActionRequest.ActionList createActionRequestActionList() {
        return new ActionRequest.ActionList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "ActionRequest")
    public JAXBElement<ActionRequest> createActionRequest(ActionRequest value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "ActionRequest"));
        return new JAXBElement<ActionRequest>(_ActionRequest_QNAME, ActionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractBaseAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "Action")
    public JAXBElement<AbstractBaseAction> createAction(AbstractBaseAction value) {
        return new JAXBElement<AbstractBaseAction>(_Action_QNAME, AbstractBaseAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerOnAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "PowerOn", substitutionHeadNamespace = "f4g/schemas/java/Actions", substitutionHeadName = "Action")
    public JAXBElement<PowerOnAction> createPowerOn(PowerOnAction value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "PowerOn"));
        return new JAXBElement<PowerOnAction>(_PowerOn_QNAME, PowerOnAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerOffAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "PowerOff", substitutionHeadNamespace = "f4g/schemas/java/Actions", substitutionHeadName = "Action")
    public JAXBElement<PowerOffAction> createPowerOff(PowerOffAction value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "PowerOff"));
        return new JAXBElement<PowerOffAction>(_PowerOff_QNAME, PowerOffAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandByAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "StandBy", substitutionHeadNamespace = "f4g/schemas/java/Actions", substitutionHeadName = "Action")
    public JAXBElement<StandByAction> createStandBy(StandByAction value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "StandBy"));
        return new JAXBElement<StandByAction>(_StandBy_QNAME, StandByAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartJobAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "StartJob", substitutionHeadNamespace = "f4g/schemas/java/Actions", substitutionHeadName = "Action")
    public JAXBElement<StartJobAction> createStartJob(StartJobAction value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "StartJob"));
        return new JAXBElement<StartJobAction>(_StartJob_QNAME, StartJobAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MoveVMAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "MoveVM", substitutionHeadNamespace = "f4g/schemas/java/Actions", substitutionHeadName = "Action")
    public JAXBElement<MoveVMAction> createMoveVM(MoveVMAction value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "MoveVM"));
        return new JAXBElement<MoveVMAction>(_MoveVM_QNAME, MoveVMAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LiveMigrateVMAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "f4g/schemas/java/Actions", name = "LiveMigrateVM", substitutionHeadNamespace = "f4g/schemas/java/Actions", substitutionHeadName = "Action")
    public JAXBElement<LiveMigrateVMAction> createLiveMigrateVM(LiveMigrateVMAction value) {
        value.setJAXBElementName(new QName("f4g/schemas/java/Actions", "LiveMigrateVM"));
        return new JAXBElement<LiveMigrateVMAction>(_LiveMigrateVM_QNAME, LiveMigrateVMAction.class, null, value);
    }

}
