//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 04:34:50 PM CEST 
//

package f4g.schemas.java.actions;

import org.joda.time.DateTime;

import f4g.schemas.java.metamodel.ServerName;

public class PowerOnAction extends AbstractBaseAction {

    protected ServerName serverName;

    public PowerOnAction() {
	super();
    }

    public PowerOnAction(ActionId id, Boolean forwarded, DateTime forwardedAt, ServerName serverName) {
	super(id, forwarded, forwardedAt);
	this.serverName = serverName;
    }

    public ServerName getServerName() {
	return serverName;
    }

    public void setNodeName(ServerName value) {
	this.serverName = value;
    }

}
