//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 04:51:12 PM CEST 
//


package java.constraints.optimizerconstraints;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Capacity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Capacity">
 *   &lt;complexContent>
 *     &lt;extension base="{java/constraints/OptimizerConstraints}PlacementConstraint">
 *       &lt;sequence>
 *         &lt;element name="MaxNbOfVMs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Capacity", propOrder = {
    "maxNbOfVMs"
})
public class Capacity
    extends PlacementConstraint
{

    @XmlElement(name = "MaxNbOfVMs")
    protected int maxNbOfVMs;

    /**
     * Gets the value of the maxNbOfVMs property.
     * 
     */
    public int getMaxNbOfVMs() {
        return maxNbOfVMs;
    }

    /**
     * Sets the value of the maxNbOfVMs property.
     * 
     */
    public void setMaxNbOfVMs(int value) {
        this.maxNbOfVMs = value;
    }

}
