//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 04:51:12 PM CEST 
//


package java.constraints.optimizerconstraints;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ClusterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClusterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cluster" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NodeController" type="{java/constraints/OptimizerConstraints}nodeControllerType"/>
 *                   &lt;element name="BoundedSLAs" type="{java/constraints/OptimizerConstraints}boundedSLAsType"/>
 *                   &lt;element name="BoundedPolicies" type="{java/constraints/OptimizerConstraints}boundedPoliciesType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClusterType", propOrder = {
    "cluster"
})
public class ClusterType {

    @XmlElement(name = "Cluster", required = true)
    protected List<ClusterType.Cluster> cluster;

    /**
     * Gets the value of the cluster property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cluster property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCluster().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClusterType.Cluster }
     * 
     * 
     */
    public List<ClusterType.Cluster> getCluster() {
        if (cluster == null) {
            cluster = new ArrayList<ClusterType.Cluster>();
        }
        return this.cluster;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NodeController" type="{java/constraints/OptimizerConstraints}nodeControllerType"/>
     *         &lt;element name="BoundedSLAs" type="{java/constraints/OptimizerConstraints}boundedSLAsType"/>
     *         &lt;element name="BoundedPolicies" type="{java/constraints/OptimizerConstraints}boundedPoliciesType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "nodeController",
        "boundedSLAs",
        "boundedPolicies"
    })
    public static class Cluster {

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "NodeController", required = true)
        protected NodeControllerType nodeController;
        @XmlElement(name = "BoundedSLAs", required = true)
        protected BoundedSLAsType boundedSLAs;
        @XmlElement(name = "BoundedPolicies", required = true)
        protected BoundedPoliciesType boundedPolicies;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the nodeController property.
         * 
         * @return
         *     possible object is
         *     {@link NodeControllerType }
         *     
         */
        public NodeControllerType getNodeController() {
            return nodeController;
        }

        /**
         * Sets the value of the nodeController property.
         * 
         * @param value
         *     allowed object is
         *     {@link NodeControllerType }
         *     
         */
        public void setNodeController(NodeControllerType value) {
            this.nodeController = value;
        }

        /**
         * Gets the value of the boundedSLAs property.
         * 
         * @return
         *     possible object is
         *     {@link BoundedSLAsType }
         *     
         */
        public BoundedSLAsType getBoundedSLAs() {
            return boundedSLAs;
        }

        /**
         * Sets the value of the boundedSLAs property.
         * 
         * @param value
         *     allowed object is
         *     {@link BoundedSLAsType }
         *     
         */
        public void setBoundedSLAs(BoundedSLAsType value) {
            this.boundedSLAs = value;
        }

        /**
         * Gets the value of the boundedPolicies property.
         * 
         * @return
         *     possible object is
         *     {@link BoundedPoliciesType }
         *     
         */
        public BoundedPoliciesType getBoundedPolicies() {
            return boundedPolicies;
        }

        /**
         * Sets the value of the boundedPolicies property.
         * 
         * @param value
         *     allowed object is
         *     {@link BoundedPoliciesType }
         *     
         */
        public void setBoundedPolicies(BoundedPoliciesType value) {
            this.boundedPolicies = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
