//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 04:14:30 PM CEST 
//


package java.constraints.optimizerconstraints;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for QoSConstraintsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QoSConstraintsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaxServerCPULoad" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaxVirtualLoadPerCore" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaxVirtualCPUPerCore" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaxServerAvg_vCPUperCore" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaxServerAvg_vRAMperPhyRAM" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Max_vRAMperPhyRAM" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bandwidth" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaxVMperServer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QoSConstraintsType", propOrder = {
    "maxServerCPULoad",
    "maxVirtualLoadPerCore",
    "maxVirtualCPUPerCore",
    "maxServerAvgVCPUperCore",
    "maxServerAvgVRAMperPhyRAM",
    "maxVRAMperPhyRAM",
    "bandwidth",
    "maxVMperServer"
})
public class QoSConstraintsType {

    @XmlElement(name = "MaxServerCPULoad")
    protected QoSConstraintsType.MaxServerCPULoad maxServerCPULoad;
    @XmlElement(name = "MaxVirtualLoadPerCore")
    protected QoSConstraintsType.MaxVirtualLoadPerCore maxVirtualLoadPerCore;
    @XmlElement(name = "MaxVirtualCPUPerCore")
    protected QoSConstraintsType.MaxVirtualCPUPerCore maxVirtualCPUPerCore;
    @XmlElement(name = "MaxServerAvg_vCPUperCore")
    protected QoSConstraintsType.MaxServerAvgVCPUperCore maxServerAvgVCPUperCore;
    @XmlElement(name = "MaxServerAvg_vRAMperPhyRAM")
    protected QoSConstraintsType.MaxServerAvgVRAMperPhyRAM maxServerAvgVRAMperPhyRAM;
    @XmlElement(name = "Max_vRAMperPhyRAM")
    protected QoSConstraintsType.MaxVRAMperPhyRAM maxVRAMperPhyRAM;
    @XmlElement(name = "Bandwidth")
    protected QoSConstraintsType.Bandwidth bandwidth;
    @XmlElement(name = "MaxVMperServer")
    protected QoSConstraintsType.MaxVMperServer maxVMperServer;

    /**
     * Gets the value of the maxServerCPULoad property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxServerCPULoad }
     *     
     */
    public QoSConstraintsType.MaxServerCPULoad getMaxServerCPULoad() {
        return maxServerCPULoad;
    }

    /**
     * Sets the value of the maxServerCPULoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxServerCPULoad }
     *     
     */
    public void setMaxServerCPULoad(QoSConstraintsType.MaxServerCPULoad value) {
        this.maxServerCPULoad = value;
    }

    /**
     * Gets the value of the maxVirtualLoadPerCore property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxVirtualLoadPerCore }
     *     
     */
    public QoSConstraintsType.MaxVirtualLoadPerCore getMaxVirtualLoadPerCore() {
        return maxVirtualLoadPerCore;
    }

    /**
     * Sets the value of the maxVirtualLoadPerCore property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxVirtualLoadPerCore }
     *     
     */
    public void setMaxVirtualLoadPerCore(QoSConstraintsType.MaxVirtualLoadPerCore value) {
        this.maxVirtualLoadPerCore = value;
    }

    /**
     * Gets the value of the maxVirtualCPUPerCore property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxVirtualCPUPerCore }
     *     
     */
    public QoSConstraintsType.MaxVirtualCPUPerCore getMaxVirtualCPUPerCore() {
        return maxVirtualCPUPerCore;
    }

    /**
     * Sets the value of the maxVirtualCPUPerCore property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxVirtualCPUPerCore }
     *     
     */
    public void setMaxVirtualCPUPerCore(QoSConstraintsType.MaxVirtualCPUPerCore value) {
        this.maxVirtualCPUPerCore = value;
    }

    /**
     * Gets the value of the maxServerAvgVCPUperCore property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxServerAvgVCPUperCore }
     *     
     */
    public QoSConstraintsType.MaxServerAvgVCPUperCore getMaxServerAvgVCPUperCore() {
        return maxServerAvgVCPUperCore;
    }

    /**
     * Sets the value of the maxServerAvgVCPUperCore property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxServerAvgVCPUperCore }
     *     
     */
    public void setMaxServerAvgVCPUperCore(QoSConstraintsType.MaxServerAvgVCPUperCore value) {
        this.maxServerAvgVCPUperCore = value;
    }

    /**
     * Gets the value of the maxServerAvgVRAMperPhyRAM property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxServerAvgVRAMperPhyRAM }
     *     
     */
    public QoSConstraintsType.MaxServerAvgVRAMperPhyRAM getMaxServerAvgVRAMperPhyRAM() {
        return maxServerAvgVRAMperPhyRAM;
    }

    /**
     * Sets the value of the maxServerAvgVRAMperPhyRAM property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxServerAvgVRAMperPhyRAM }
     *     
     */
    public void setMaxServerAvgVRAMperPhyRAM(QoSConstraintsType.MaxServerAvgVRAMperPhyRAM value) {
        this.maxServerAvgVRAMperPhyRAM = value;
    }

    /**
     * Gets the value of the maxVRAMperPhyRAM property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxVRAMperPhyRAM }
     *     
     */
    public QoSConstraintsType.MaxVRAMperPhyRAM getMaxVRAMperPhyRAM() {
        return maxVRAMperPhyRAM;
    }

    /**
     * Sets the value of the maxVRAMperPhyRAM property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxVRAMperPhyRAM }
     *     
     */
    public void setMaxVRAMperPhyRAM(QoSConstraintsType.MaxVRAMperPhyRAM value) {
        this.maxVRAMperPhyRAM = value;
    }

    /**
     * Gets the value of the bandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.Bandwidth }
     *     
     */
    public QoSConstraintsType.Bandwidth getBandwidth() {
        return bandwidth;
    }

    /**
     * Sets the value of the bandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.Bandwidth }
     *     
     */
    public void setBandwidth(QoSConstraintsType.Bandwidth value) {
        this.bandwidth = value;
    }

    /**
     * Gets the value of the maxVMperServer property.
     * 
     * @return
     *     possible object is
     *     {@link QoSConstraintsType.MaxVMperServer }
     *     
     */
    public QoSConstraintsType.MaxVMperServer getMaxVMperServer() {
        return maxVMperServer;
    }

    /**
     * Sets the value of the maxVMperServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSConstraintsType.MaxVMperServer }
     *     
     */
    public void setMaxVMperServer(QoSConstraintsType.MaxVMperServer value) {
        this.maxVMperServer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Bandwidth {

        @XmlValue
        protected double value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxServerAvgVCPUperCore {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxServerAvgVRAMperPhyRAM {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxServerCPULoad {

        @XmlValue
        protected double value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxVMperServer {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxVRAMperPhyRAM {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxVirtualCPUPerCore {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxVirtualLoadPerCore {

        @XmlValue
        protected double value;
        @XmlAttribute(name = "priority")
        protected Integer priority;

        /**
         * Gets the value of the value property.
         * 
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPriority() {
            if (priority == null) {
                return  1;
            } else {
                return priority;
            }
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

    }

}
